/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as StackRouteImport } from './routes/stack'
import { Route as SortingRouteImport } from './routes/sorting'
import { Route as SearchingRouteImport } from './routes/searching'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as LinkedListRouteImport } from './routes/linked-list'
import { Route as HeapRouteImport } from './routes/heap'
import { Route as HashTableRouteImport } from './routes/hash-table'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ArrayRouteImport } from './routes/array'
import { Route as IndexRouteImport } from './routes/index'

const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const StackRoute = StackRouteImport.update({
  id: '/stack',
  path: '/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchingRoute = SearchingRouteImport.update({
  id: '/searching',
  path: '/searching',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkedListRoute = LinkedListRouteImport.update({
  id: '/linked-list',
  path: '/linked-list',
  getParentRoute: () => rootRouteImport,
} as any)
const HeapRoute = HeapRouteImport.update({
  id: '/heap',
  path: '/heap',
  getParentRoute: () => rootRouteImport,
} as any)
const HashTableRoute = HashTableRouteImport.update({
  id: '/hash-table',
  path: '/hash-table',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrayRoute = ArrayRouteImport.update({
  id: '/array',
  path: '/array',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
  '/tree': typeof TreeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/array': typeof ArrayRoute
  '/graph': typeof GraphRoute
  '/hash-table': typeof HashTableRoute
  '/heap': typeof HeapRoute
  '/linked-list': typeof LinkedListRoute
  '/queue': typeof QueueRoute
  '/searching': typeof SearchingRoute
  '/sorting': typeof SortingRoute
  '/stack': typeof StackRoute
  '/tree': typeof TreeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/array'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/searching'
    | '/sorting'
    | '/stack'
    | '/tree'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/array'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/searching'
    | '/sorting'
    | '/stack'
    | '/tree'
  id:
    | '__root__'
    | '/'
    | '/array'
    | '/graph'
    | '/hash-table'
    | '/heap'
    | '/linked-list'
    | '/queue'
    | '/searching'
    | '/sorting'
    | '/stack'
    | '/tree'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrayRoute: typeof ArrayRoute
  GraphRoute: typeof GraphRoute
  HashTableRoute: typeof HashTableRoute
  HeapRoute: typeof HeapRoute
  LinkedListRoute: typeof LinkedListRoute
  QueueRoute: typeof QueueRoute
  SearchingRoute: typeof SearchingRoute
  SortingRoute: typeof SortingRoute
  StackRoute: typeof StackRoute
  TreeRoute: typeof TreeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stack': {
      id: '/stack'
      path: '/stack'
      fullPath: '/stack'
      preLoaderRoute: typeof StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searching': {
      id: '/searching'
      path: '/searching'
      fullPath: '/searching'
      preLoaderRoute: typeof SearchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linked-list': {
      id: '/linked-list'
      path: '/linked-list'
      fullPath: '/linked-list'
      preLoaderRoute: typeof LinkedListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heap': {
      id: '/heap'
      path: '/heap'
      fullPath: '/heap'
      preLoaderRoute: typeof HeapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hash-table': {
      id: '/hash-table'
      path: '/hash-table'
      fullPath: '/hash-table'
      preLoaderRoute: typeof HashTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/array': {
      id: '/array'
      path: '/array'
      fullPath: '/array'
      preLoaderRoute: typeof ArrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrayRoute: ArrayRoute,
  GraphRoute: GraphRoute,
  HashTableRoute: HashTableRoute,
  HeapRoute: HeapRoute,
  LinkedListRoute: LinkedListRoute,
  QueueRoute: QueueRoute,
  SearchingRoute: SearchingRoute,
  SortingRoute: SortingRoute,
  StackRoute: StackRoute,
  TreeRoute: TreeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
